---------------------------------------------------------------------------
-- DO NOT EDIT THIS FILE
---------------------------------------------------------------------------
XRPLifeDB = {}

XRPLifeDB["player"] = {}
XRPLifeDB["character"] = {}
XRPLifeDB["clothing"] = {}
XRPLifeDB["inventory"] = {}