--------------------------------------------------------------------------------------------------------------------------------------------------------
-----[[ DO NOT EDIT THIS FILE !!!!!!!!!!!!!!!! ]]-----
--------------------------------------------------------------------------------------------------------------------------------------------------------
XRPLifeTables = {}

XRPLifeTables["players"] = {}
XRPLifeTables["players"].list = {}
XRPLifeTables["players"].methods = {}

XRPLifeTables["characters"] = {}
XRPLifeTables["characters"].list = {}
XRPLifeTables["characters"].methods = {}

XRPLifeTables["vehicles"] = {}
XRPLifeTables["vehicles"].list = {}
XRPLifeTables["vehicles"].methods = {}